### ISSUE TITLE
firebase_storage_image need an old version of firebase_storage

### ISSUE THREAD

**Issue by MatsAndT** [axross/firebase_storage_image#5]
```
Running "flutter packages get" in "app_name"...

Because every version of firebase_storage_image depends on firebase_storage ^1.0.4 and "app_name" depends on firebase_storage ^2.1.0, firebase_storage_image is forbidden.
So, because "app_name" depends on firebase_storage_image any, version solving failed.
```

```
dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^0.8.1
  firebase_core: ^0.3.1
  cloud_firestore: ^0.9.5
  firebase_storage: ^2.1.0
  firebase_storage_image: 
```

is it possible to make firebase_storage_image use the latest version of firebase_storage?
